### ISSUE TITLE
Timestamps can be different by ~1 second

### ISSUE THREAD

**Issue by MTres19** [MTres19/mw-extension-git#18]
For example, moving a page is noted in the revision and logging tables. However, the revision table's timestamp was, in my case, 1 second earlier than the timestamp in the logging table. This could cause some problems because only later revisions would have the new title, and if the next edit was made with Git there could be conflicts. This is related to #16.

**Comment by konstin** [comment]
I don't know about the details, but afaik you shouldn't need to use e.g. the logging tables. Just stick with one table which you map and don't care about the rest. This makes the extension also more stable againt changes in the mediawiki internals.

**Comment by MTres19** [comment]
That can't work. Page titles aren't stored with revisions and if you make
retroactive changes the hashes will all be different for every commit
afterward. MediaWiki does a bad job keeping track of how things *used* to
be, and examining the logging table is the only way to figure it out.
